version: "3.8"

services:
  ssh-tunnel:
    build:
      context: .
      dockerfile: Dockerfile.ssh-tunnel
    container_name: ssh-tunnel
    ports:
      - "3307:3307"
    volumes:
      - ./secrets/ssh_key:/root/.ssh/id_rsa
      - ./ssh_config:/root/.ssh/config

  pokepocket-app:
    image: 207309871349.dkr.ecr.us-east-1.amazonaws.com/pokepocket-app:latest
    container_name: pokepocket-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - ssh-tunnel
    links:
      - ssh-tunnel
