version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root          # Set the root password
      MYSQL_DATABASE: pokepocket         # Set the default database name
      MYSQL_USER: user                   # Create a user with access to the database
      MYSQL_PASSWORD: 1234               # Set the user's password
    ports:
      - "3306:3306"  # Expose MySQL port to the host machine
    networks:
      - pokepocket-network
    restart: always  # Restart the container automatically
    hostname: mysql-db-host

networks:
  pokepocket-network:
    driver: bridge

volumes:
  mysql-data:
