# version: '3.8'

# services:
#   db:
#     image: mysql:8.0
#     container_name: mysql-db
#     environment:
#       MYSQL_ROOT_PASSWORD: root          # Set the root password
#       MYSQL_DATABASE: pokepocket         # Set the default database name
#     ports:
#       - "3306:3306"  # Expose MySQL port to the host machine
#     networks:
#       - pokepocket-network
#     restart: always  # Restart the container automatically
#     hostname: mysql-db-host
#     volumes:
#       - mysql-data:/var/lib/mysql

# networks:
#   pokepocket-network:
#     driver: bridge

# volumes:
#   mysql-data: {}

version: '3.8'

services:
  ssh-tunnel:
    image: alpine:latest
    restart: always
    command: >
      sh -c "apk add --no-cache openssh-client netcat-openbsd &&
             mkdir -p /root/.ssh &&
             chmod 700 /root/.ssh &&
             cp /run/secrets/ssh_key /root/.ssh/id_rsa &&
             chmod 600 /root/.ssh/id_rsa &&
             cp /tmp/ssh_config /root/.ssh/config &&
             chmod 600 /root/.ssh/config &&
             echo 'Starting SSH tunnel...' &&
             ssh -o StrictHostKeyChecking=no -N -L 0.0.0.0:3307:mysql.cise.ufl.edu:3306 dfranco1@rain.cise.ufl.edu"
    volumes:
      - ./ssh_config:/tmp/ssh_config:ro
    secrets:
      - ssh_key
    healthcheck:
      test: "nc -z localhost 3307 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3307:3307"
    networks:
      - pokepocket-network

  app:
    build: .
    depends_on:
      ssh-tunnel:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ssh-tunnel:3307/poke_pocket
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - pokepocket-network

networks:
  pokepocket-network:
    driver: bridge

secrets:
  ssh_key:
    file: ./secrets/ssh_key
  db_username:
    file: ./secrets/db_username.txt
  db_password:
    file: ./secrets/db_password.txt